### ISSUE TITLE
question: why return theme instead of having theme public

### ISSUE THREAD

**Issue by bashbunni** [caarlos0/catppuccin-go#3]
hihi I'm wondering why [here](https://github.com/catppuccin/go/blob/main/main.go#L51) we have a public function returning the theme instead of just having the theme struct be public?

**Comment by caarlos0** [comment]
yes, I think we can change this, its one of the reasons I haven't cut a tag yet. Will do

**Comment by caarlos0** [comment]
@bashbunni  #4

**Comment by bashbunni** [comment]
Ah ok, I just wasn't sure if there was something I didn't know about that I could learn from 😂 Thanks for letting me know @caarlos0 !!
