### ISSUE TITLE
do we want a "get" variant by name function?

### ISSUE THREAD

**Issue by caarlos0** [caarlos0/catppuccin-go#5]
something like:

```go
func Get(variant string) Theme {
	for _, t := range []Theme{
		Mocha,
		Frappe,
		Macchiato,
		Latte,
	} {
		if t.Name() == variant {
			return t
		}
	}
	return nil
}
```

Not sure if it makes sense or not... wonder what y'all think

**Comment by jolheiser** [comment]
Might want `EqualFold` here so `mocha` v `Mocha` works, but otherwise I think it would be fine. 
I'd imagine there will be a number of cases where there will be a string->theme conversion.
